### ISSUE TITLE
Undeclared global variable

### ISSUE THREAD

**Issue by jhcole** [FozLand/shooter#1]
Undeclared global variable "id" accessed at /home/foz/.minetest/mods/shooter/flaregun.lua:71

EDIT: This seems trivial and isn't causing any known problems so I opened the issue with upstream stujones11/shooter#20

**Comment by mootpoint** [comment]
[fixed](https://github.com/stujones11/shooter/commit/2e23f40f9a5cbedfc5c145c56df7b79d37d8314d)
